version: '2.1'
services:
    web:
        build: .
        image: padroes/web
        container_name: web
        ports:
          - "8081:8080"
        depends_on:
            banco:
                condition: service_healthy
        links:
            - "banco:host-banco"
        healthcheck:
            test: "exit 0"
    banco:
        build: ./postgres
        image: padroes/banco
        container_name: banco
        ports:
            - "5433:5432"
        healthcheck:
            test: "exit 0"
